#!/usr/bin/env bash
# Push the launch .env to the box.
#
# Secrets come from the local repo-root .env; the sized VPS settings (rooms,
# build cap, retention, public URLs) come from ops/env.launch.template. The
# two are concatenated and streamed straight into the box over ssh — no values
# are ever printed, and no plaintext copy is left in /tmp on either end.
#
# The box copy lives at /etc/zenkai/env, ROOT-owned and 0600, injected by the
# systemd units (EnvironmentFile=). It is NOT a repo-root .env any more: that
# file was readable by the zenkai user, so a generator or test child running as
# zenkai could read every secret straight off disk. This script also removes any
# leftover repo-root .env on the box. Requires an ssh login that is root (it
# already chowns), which the existing zenkai-box login is.
#
# Exists because the equivalent one-liner is long enough that terminals wrap
# it mid-token, and a wrapped `.env` argument silently becomes its own command.
#
#   bash ops/push-env.sh [ssh-host]     # default host: zenkai-box
#
# Re-run it any time a key rotates; it overwrites the whole file.
set -euo pipefail

HOST="${1:-zenkai-box}"
DEST="/etc/zenkai/env"
OLD_ENV="/home/zenkai/Zenkai/.env"
cd "$(dirname "$0")/.."

[ -f .env ] || { echo "no .env at the repo root — nothing to push"; exit 1; }

# Fail before touching the box if a required value is missing or empty.
missing=0
for k in ANTHROPIC_API_KEY IP_SUPABASE_URL IP_SUPABASE_ANON_KEY \
         IP_SUPABASE_SERVICE_KEY IP_AUTH_ADMIN_EMAILS; do
  grep -qE "^${k}=[^[:space:]]" .env || { echo "missing or empty: ${k}"; missing=1; }
done
[ "${missing}" -eq 0 ] || exit 1

# IP_GMAIL_* is the welcome sweep (welcome.ts). It belongs HERE and not in
# env.launch.template because the template is committed and this is a
# credential — and because a sweep whose keys never reached the box fails
# invisibly: the timer fires every 5 minutes and exits 2 into the journal.
SECRETS='^(ANTHROPIC_API_KEY|ELEVENLABS_API_KEY|IP_SUPABASE_URL|IP_SUPABASE_ANON_KEY|IP_SUPABASE_SERVICE_KEY|IP_AUTH_ADMIN_EMAILS|IP_GMAIL_USER|IP_GMAIL_APP_PASSWORD|IP_WELCOME_FROM|IP_WELCOME_REPLY_TO)='

# The stream is sanitized (sed below) before it lands: systemd EnvironmentFile
# does not strip trailing inline comments the way node's loadEnvFile did, so a
# `KEY=value # note` line in .env would otherwise poison the value on the box.
{
  echo "# Generated by ops/push-env.sh — edit the local .env and re-run, not this file."
  grep -hE "${SECRETS}" .env
  echo
  # Everything else in the template is non-secret and already sized for the box.
  grep -hE '^IP_' ops/env.launch.template | grep -vE 'SUPABASE|AUTH_ADMIN'
} | sed -E 's/[[:space:]]+#.*$//' | ssh "${HOST}" "umask 077; mkdir -p /etc/zenkai && dd of='${DEST}' status=none && chown root:root '${DEST}' && chmod 600 '${DEST}' && rm -f '${OLD_ENV}' && echo \"installed \$(grep -c '=' '${DEST}') settings to ${DEST} (root:root 0600); removed old ${OLD_ENV}\""
