#!/usr/bin/env bash
# Push the launch .env to the box.
#
# Secrets come from the local repo-root .env; the sized VPS settings (rooms,
# build cap, retention, public URLs) come from ops/env.launch.template. The
# two are concatenated and streamed straight into the box over ssh — no values
# are ever printed, and no plaintext copy is left in /tmp on either end.
#
# Exists because the equivalent one-liner is long enough that terminals wrap
# it mid-token, and a wrapped `.env` argument silently becomes its own command.
#
#   bash ops/push-env.sh [ssh-host]     # default host: zenkai-box
#
# Re-run it any time a key rotates; it overwrites the whole file.
set -euo pipefail

HOST="${1:-zenkai-box}"
DEST="/home/zenkai/Zenkai/.env"
cd "$(dirname "$0")/.."

[ -f .env ] || { echo "no .env at the repo root — nothing to push"; exit 1; }

# Fail before touching the box if a required value is missing or empty.
missing=0
for k in ANTHROPIC_API_KEY IP_SUPABASE_URL IP_SUPABASE_ANON_KEY \
         IP_SUPABASE_SERVICE_KEY IP_AUTH_ADMIN_EMAILS; do
  grep -qE "^${k}=[^[:space:]]" .env || { echo "missing or empty: ${k}"; missing=1; }
done
[ "${missing}" -eq 0 ] || exit 1

# IP_GMAIL_* is the welcome sweep (welcome.ts). It belongs HERE and not in
# env.launch.template because the template is committed and this is a
# credential — and because a sweep whose keys never reached the box fails
# invisibly: the timer fires every 5 minutes and exits 2 into the journal.
SECRETS='^(ANTHROPIC_API_KEY|ELEVENLABS_API_KEY|IP_SUPABASE_URL|IP_SUPABASE_ANON_KEY|IP_SUPABASE_SERVICE_KEY|IP_AUTH_ADMIN_EMAILS|IP_GMAIL_USER|IP_GMAIL_APP_PASSWORD|IP_WELCOME_FROM|IP_WELCOME_REPLY_TO)='

{
  echo "# Generated by ops/push-env.sh — edit the local .env and re-run, not this file."
  grep -hE "${SECRETS}" .env
  echo
  # Everything else in the template is non-secret and already sized for the box.
  grep -hE '^IP_' ops/env.launch.template | grep -vE 'SUPABASE|AUTH_ADMIN'
} | ssh "${HOST}" "umask 077; dd of='${DEST}' status=none && chown zenkai:zenkai '${DEST}' && echo \"installed \$(grep -c '=' '${DEST}') settings\""
